### ISSUE TITLE
Prefix is too long

### ISSUE THREAD

**Issue by Aemrodd** [bkader/Skada-Cata#1]
**Describe the bug**
After finding out that you created your Skada Revisited for Cata as well, I immediately downloaded it and everything ran fine as far as I could see. I saw minor LUA errors which I decided to ignore, because nothing seemed to be broken. Though after some time I realized that some of my WeakAuras stopped working (correctly). 
I deactivated all AddOns despite BugSack: No Errors
I activated only Skada + BugSack: Same LUA Errors as pasted below
Skada + BugSack + WeakAuras: Same LUA Errors

**Error Log**

```
4x Prefix is too long
<in C code>
<in C code>
Libraries\Ace3\16AceComm-3.0-12\ChatThrottleLib-24.nil.lua:310: in function "Despool"
Libraries\Ace3\16AceComm-3.0-12\ChatThrottleLib-24.nil.lua:378: in function <Libraries\Ace3\AceComm-3.0\ChatThrottleLib.lua:335>

Locals:
(*temporary) = "LibGroupTalents-1.0"
(*temporary) = "HELLO 65"
(*temporary) = "PARTY"
 = <func> =[C]:-1
 = <func> @BugSack\Libs\AceComm-3.0\ChatThrottleLib.lua:216

```

**Comment by bkader** [comment]
Hello @Aemrodd .. Try without **BugSack** and with Skada only, the issue appears to be caused by `ChatThrottleLib-v24`, also, the error is vague and doesn't help.

**Comment by Artur91425** [comment]
@bkader,

https://wowwiki-archive.fandom.com/wiki/API_SendAddonMessage
```
prefix
    String - Message prefix, can be used as your addon identifier. (16 Character Limit)
```

https://github.com/bkader/Skada-Cata/blob/main/Skada/Libs/LibCompat-1.0/Libs/LibGroupTalents-1.0/LibGroupTalents-1.0.lua#L1341
and
https://github.com/bkader/Skada-Cata/blob/main/Skada/Libs/LibCompat-1.0/Libs/LibGroupTalents-1.0/LibGroupTalents-1.0.lua#L1343
This lines is causing an error. When calling `SendAddonMessage`, the prefix argument - `MAJOR`.
`MAJOR` is declared at the beginning of the library and it has the value `LibGroupTalents-1.0`:
https://github.com/bkader/Skada-Cata/blob/main/Skada/Libs/LibCompat-1.0/Libs/LibGroupTalents-1.0/LibGroupTalents-1.0.lua#L69

The number of characters is clearly more than 16. To fix the error, you need to change the prefix. For example, set it as `LibGroupTalents`

**I think this is also relevant for WOTLK.**
