### ISSUE TITLE
Skada appears as out of dated on 4.3.4 (15595) client

### ISSUE THREAD

**Issue by CraftedRO** [bkader/Skada-Cata#2]
**Describe the bug**
Skada appears as out of dated on 4.3.4 (15595) client
Also after login isn't loaded.

**To Reproduce**
1. Go to 'wow.exe'
2. Click on 'addons'

**Expected behavior**
It shoud be loaded and not appear out of dated on cata 4.3 client.

**SS**
![WoWScrnShot_020223_175757](https://user-images.githubusercontent.com/24683355/216375762-e8b5340c-c93f-4188-a47c-847115f216ee.jpg)
**Additional context**

**Error Log**

```

```

**Comment by bkader** [comment]
![image](https://user-images.githubusercontent.com/4732702/216379116-cabbf300-5618-4a08-9f43-dbd97dce3595.png)

**Comment by CraftedRO** [comment]
and it still doesn't load ingame dude

**Comment by CraftedRO** [comment]
seems not it works, for some reason after deleting cache folder

**Comment by CraftedRO** [comment]
seems now it works, for some reason after deleting cache folder
